import Navbar from "@/component/common/Navbar";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import 'react-toastify/dist/ReactToastify.css'; // Import the CSS
import { ToastContainer } from 'react-toastify'; // Import the ToastContainer


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <NextAuthProvider>
          <ToastContainer />
          <Navbar />
          {children}   </NextAuthProvider>
      </body>
    </html>
  );
}
